[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"

[window]
padding.x = 5
padding.y = 0
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.99
blur = true
option_as_alt = "Both"

[font]
#family = "Cousine"#"MesloLGS Nerd Font Mono"
size = 10

[font.bold]
family = "JetBrainsMono NFM"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NFM"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NFM"
style = "Italic"

[font.normal]
family = "JetBrainsMono NFM"
style = "Regular"


[general]
import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[keyboard]
bindings = [
   { key = "Return", mods = "Shift|Super", action = "SpawnNewInstance" },
    { key = "Plus", mods = "Shift|Super", action = "IncreaseFontSize" },
    { key = "_", mods = "Shift|Super", action = "DecreaseFontSize" },
    { key = "=", mods = "Super", action = "ResetFontSize" }
]

[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
text = '#000000'
cursor = '#ffffff'

[colors.selection]
text = '#000000'
background = '#fffacd'

[colors.primary]
    background = '#000000'
    foreground = '#e0e0e0'

[colors.normal]
    black =   '#3f3f3f'
    red =     '#b06060'
    green =   '#60b47a'
    yellow =  '#dfaf8f'
    blue =    '#506080'
    magenta = '#dc9cc3'
    cyan =    '#8cd0d8'
    white =   '#ffffff'

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

#[[hints.enabled]]
#regex = "[^\\s]+\\.(java):\\[\\d+,\\d+\\]"
#command = { program = "bash", args = ["-c", "f=$(echo $0 | cut -d: -f1); l=$(echo $0 | grep -o '\\[\\d\\+' | tr -d '['); alacritty -e nvim +$l $f"] }
#mouse = { enabled = true }

[[hints.enabled]]
regex = "[^\\s]+\\.(rs|java):\\[\\d+,\\d+\\]"
command = { program = "bash", args = ["-c", "f=$(echo $0 | cut -d: -f1); pos=$(echo $0 | sed 's/.*\\[\\([0-9]*\\),\\([0-9]*\\)\\].*/\\1,\\2/'); alacritty -e nvim \"+call cursor($pos)\" $f"] }
mouse = { enabled = true }
